RO0:
     IP: RO
     IP_specs:
         first_instance_name: 'design_1_i/RO0/inst/RO[#].nolabel_line95/LUT6_2_inst'
         other_instance_names: 'design_1_i/RO0/inst/RO[#].notGate[#].Inverter/LUT6_inst'
         feedback_signal: 'design_1_i/RO0/inst/RO[#].notGate[0].Inverter/out_sig'
         Num_Oscillators: 32
         Num_Stages: 3
