# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_1_wrapper.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_HCI_0_6/design_1_AXI_HCI_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_HCI_0_6 || ORIG_REF_NAME==design_1_AXI_HCI_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Arm_Core_axi_periph_4/design_1_Arm_Core_axi_periph_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Arm_Core_axi_periph_4 || ORIG_REF_NAME==design_1_Arm_Core_axi_periph_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_Arm_Core_100M_3/design_1_rst_Arm_Core_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_Arm_Core_100M_3 || ORIG_REF_NAME==design_1_rst_Arm_Core_100M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_Arm_Core_100M_3/design_1_rst_Arm_Core_100M_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_Arm_Core_100M_3 || ORIG_REF_NAME==design_1_rst_Arm_Core_100M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_Arm_Core_100M_3/design_1_rst_Arm_Core_100M_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_Arm_Core_100M_3 || ORIG_REF_NAME==design_1_rst_Arm_Core_100M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_Arm_Core_100M_3/design_1_rst_Arm_Core_100M_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
